// scaffold.go — generate cel/tests fixture skeletons for cac-content rules.
//
// Fixtures should be seeded from REAL API objects, never hand-invented shapes:
// resource schemas differ across versions (e.g. HyperConverged featureGates is
// an object on v1beta1 but an array on v1, and nonRoot was removed in 4.18+).
// `cac scaffold --from-cluster` fetches each input through the rule's own
// kubernetes_input_spec — the same fetch the scanner performs — sanitizes the
// result, and stamps the fixture file with provenance (versions only, nothing
// cluster-identifiable).
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// fixtureProvenance records where fixture data came from. Versions only — no
// hostnames, domains, or other cluster-identifiable information.
type fixtureProvenance struct {
	FetchedWith       string            `yaml:"fetched_with"`
	Date              string            `yaml:"date"`
	OpenshiftVersion  string            `yaml:"openshift_version,omitempty"`
	KubernetesVersion string            `yaml:"kubernetes_version,omitempty"`
	SourceAPIVersions map[string]string `yaml:"source_api_versions,omitempty"`
}

// fixtureFile is the wrapper fixture format: provenance + cases. Bare-list
// fixture files (just the cases) remain valid — see loadCases.
type fixtureFile struct {
	Provenance *fixtureProvenance `yaml:"provenance,omitempty"`
	Cases      []cacCase          `yaml:"cases"`
}

func cacScaffold(args []string) int {
	fs := newFlags("cac scaffold")
	fromCluster := fs.Bool("from-cluster", false, "seed fixtures from live objects fetched via each input's kubernetes_input_spec (kubectl)")
	keepStatus := fs.Bool("keep-status", false, "keep .status in fetched objects (deep-stripped of uid/resourceVersion); default drops it")
	force := fs.Bool("force", false, "overwrite an existing scaffolded fixtures file")
	maxItems := fs.Int("max-items", 3, "cap the number of fetched items per list input")
	fs.Parse(reorderArgs(args))
	path := fs.Arg(0)
	if path == "" {
		return fail("usage: celctl cac scaffold <rule-dir|shared.yml> [--from-cluster] [--force]")
	}
	rule, err := loadCacRule(path)
	if err != nil {
		return fail("%v", err)
	}

	testsDir := filepath.Join(rule.dir, "cel", "tests")
	outPath := filepath.Join(testsDir, "cases.yaml")
	if _, err := os.Stat(outPath); err == nil && !*force {
		return fail("%s already exists (use --force to overwrite)", outPath)
	}

	prov := &fixtureProvenance{
		Date:              time.Now().UTC().Format("2006-01-02"),
		SourceAPIVersions: map[string]string{},
	}
	seed := map[string]interface{}{}

	if *fromCluster {
		prov.FetchedWith = "celctl cac scaffold --from-cluster"
		prov.KubernetesVersion, prov.OpenshiftVersion = clusterVersions()
		for _, in := range rule.Inputs {
			data, err := cacKubectlFetch(in.Spec)
			if err != nil {
				return fail("fetch %q: %v (no cluster? rerun without --from-cluster for an offline skeleton)", in.Name, err)
			}
			data = capListItems(in.normalizeBinding(sanitizeObject(data, *keepStatus)), *maxItems)
			seed[in.Name] = data
			prov.SourceAPIVersions[in.Name] = servedAPIVersion(data, in.Spec)
			fmt.Printf("  fetched %s (%s)\n", in.Name, describeBinding(data))
		}
	} else {
		prov.FetchedWith = "celctl cac scaffold (offline skeleton — field values are placeholders, replace with real object data)"
		for _, in := range rule.Inputs {
			seed[in.Name] = in.emptyBinding()
			prov.SourceAPIVersions[in.Name] = in.Spec.APIVersion + " (declared, not fetched)"
		}
	}

	ff := fixtureFile{
		Provenance: prov,
		Cases: []cacCase{
			{Name: "TODO compliant case — expected cluster state", Expect: true, Inputs: deepCopyInputs(seed)},
			{Name: "TODO non-compliant case — mutate the interesting field", Expect: false, Inputs: deepCopyInputs(seed)},
		},
	}
	// Empty/absent edge case for list inputs: all() over [] is vacuously true.
	for _, in := range rule.Inputs {
		if in.Spec.ResourceName == "" {
			empty := deepCopyInputs(seed)
			empty[in.Name] = map[string]interface{}{"apiVersion": "v1", "kind": "List", "items": []interface{}{}}
			ff.Cases = append(ff.Cases, cacCase{
				Name:   fmt.Sprintf("TODO empty %s — decide: is an empty cluster compliant?", in.Name),
				Expect: true,
				Inputs: empty,
			})
			break
		}
	}

	if err := os.MkdirAll(testsDir, 0o755); err != nil {
		return fail("%v", err)
	}
	b, err := yaml.Marshal(&ff)
	if err != nil {
		return fail("%v", err)
	}
	header := "# CEL rule fixtures — generated by celctl cac scaffold.\n" +
		"# Fill the TODO cases with real values, then run: celctl cac test " + rule.dir + "\n" +
		"# Review for cluster-identifiable values before committing (versions are OK).\n"
	if err := os.WriteFile(outPath, []byte(header+string(b)), 0o644); err != nil {
		return fail("%v", err)
	}
	fmt.Printf("wrote %s (%d cases)\n", outPath, len(ff.Cases))
	if *fromCluster {
		fmt.Println("⚠️  review the fixture for cluster-identifiable values before committing")
	}
	return 0
}

// sanitizeObject strips server-managed noise from a fetched object (and each
// item of a fetched List) so fixtures stay small and stable. status is dropped
// unless keepStatus is set (rules rarely read it, and e.g. HyperConverged's
// status.relatedObjects carries uid/resourceVersion for every related object);
// when kept it is deep-stripped of uid/resourceVersion.
func sanitizeObject(v interface{}, keepStatus bool) interface{} {
	m, ok := v.(map[string]interface{})
	if !ok {
		return v
	}
	if items, ok := m["items"].([]interface{}); ok {
		for i, it := range items {
			items[i] = sanitizeObject(it, keepStatus)
		}
		// The List wrapper's own metadata is pure noise (resourceVersion only).
		delete(m, "metadata")
		return m
	}
	if !keepStatus {
		delete(m, "status")
	} else if st, ok := m["status"]; ok {
		m["status"] = deepStripKeys(st, "uid", "resourceVersion", "managedFields")
	}
	if md, ok := m["metadata"].(map[string]interface{}); ok {
		for _, k := range []string{
			"managedFields", "uid", "resourceVersion", "generation",
			"creationTimestamp", "selfLink", "ownerReferences", "finalizers",
		} {
			delete(md, k)
		}
		if ann, ok := md["annotations"].(map[string]interface{}); ok {
			delete(ann, "kubectl.kubernetes.io/last-applied-configuration")
			if len(ann) == 0 {
				delete(md, "annotations")
			}
		}
	}
	return m
}

// deepStripKeys removes the named keys from every map at any depth.
func deepStripKeys(v interface{}, keys ...string) interface{} {
	switch x := v.(type) {
	case map[string]interface{}:
		for _, k := range keys {
			delete(x, k)
		}
		for k, val := range x {
			x[k] = deepStripKeys(val, keys...)
		}
		return x
	case []interface{}:
		for i, val := range x {
			x[i] = deepStripKeys(val, keys...)
		}
		return x
	default:
		return v
	}
}

// capListItems truncates a List binding to at most n items.
func capListItems(v interface{}, n int) interface{} {
	m, ok := v.(map[string]interface{})
	if !ok {
		return v
	}
	if items, ok := m["items"].([]interface{}); ok && n > 0 && len(items) > n {
		m["items"] = items[:n]
		fmt.Printf("  (capped to %d of %d items)\n", n, len(items))
	}
	return m
}

// servedAPIVersion prefers the apiVersion the cluster actually served over the
// one declared in the input spec.
func servedAPIVersion(v interface{}, spec cacInputSpec) string {
	if m, ok := v.(map[string]interface{}); ok {
		if items, ok := m["items"].([]interface{}); ok && len(items) > 0 {
			if it, ok := items[0].(map[string]interface{}); ok {
				if av, ok := it["apiVersion"].(string); ok && av != "" {
					return av
				}
			}
		}
		if av, ok := m["apiVersion"].(string); ok && av != "" && av != "v1" {
			return av
		}
	}
	return spec.APIVersion
}

// clusterVersions returns (kubernetesVersion, openshiftVersion) — versions
// only, never cluster-identifiable data. Failures degrade to empty strings.
func clusterVersions() (k8s, ocp string) {
	if out, err := runKubectl("version", "-o", "json"); err == nil {
		// kubectl mixes warnings into combined output; parse from the first '{'.
		if i := strings.Index(out, "{"); i >= 0 {
			var v struct {
				ServerVersion struct {
					GitVersion string `json:"gitVersion"`
				} `json:"serverVersion"`
			}
			// Decode (not Unmarshal): kubectl may append warnings after the JSON.
			if json.NewDecoder(strings.NewReader(out[i:])).Decode(&v) == nil {
				k8s = v.ServerVersion.GitVersion
			}
		}
	}
	if out, err := runKubectl("get", "clusterversion", "version",
		"-o", "jsonpath={.status.desired.version}"); err == nil {
		ocp = strings.TrimSpace(out)
	}
	return k8s, ocp
}

func deepCopyInputs(in map[string]interface{}) map[string]interface{} {
	b, err := json.Marshal(in)
	if err != nil {
		return in
	}
	var out map[string]interface{}
	if err := json.Unmarshal(b, &out); err != nil {
		return in
	}
	return out
}
